# Generated by Django 6.0.1 on 2026-02-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('aerial', 'Aerial Photography'), ('survey', 'Drone Survey'), ('inspection', 'Inspection'), ('mapping', 'Mapping'), ('other', 'Other')], max_length=20)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='projectinquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
