# Generated by Django 6.0.1 on 2026-02-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
