# Generated by Django 6.0.1 on 2026-03-08 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_review_projectinquiry_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('client_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('service_type', models.CharField(blank=True, choices=[('aerial', 'Aerial Photography'), ('survey', 'Drone Survey'), ('inspection', 'Inspection'), ('mapping', 'Mapping'), ('construction', 'Construction Tracking'), ('other', 'Other')], max_length=20)),
                ('main_image', models.ImageField(upload_to='projects/')),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.project')),
            ],
        ),
    ]
